# When editing this file, remember that http://www.yamllint.com is your friend :-)
---

driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    driver_config:
      network:
      - ["private_network", {ip: "192.168.33.23"}]

    driver:
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.2_chef-provisionerless.box


suites:
  - name: community-edition
    run_list:
      - recipe[alfresco::default]
      - recipe[alfresco::redeploy]
    verifier:
      inspec_tests:
        - name: nginx-hardening
          git: https://github.com/Alfresco/tests-nginx-hardening
    data_bags_path: "test/integration/data_bags"
    attributes: {
      "name": "chef-alfresco-community",
      "hostname": "alfresco-allinone-test",
      "alfresco" : {
        "components" : ['haproxy','nginx','tomcat','transform','repo','share','solr','mysql','googledocs','yourkit'],
        "version" : "5.1.g",
        "ssl_enabled" : false
      },
      "nginx" : {
        "use_nossl_config" : true
      }
     }
  - name: community-52
    run_list:
      - recipe[alfresco::default]
      - recipe[alfresco::redeploy]
    verifier:
      inspec_tests:
        - name: nginx-hardening
          git: https://github.com/Alfresco/tests-nginx-hardening
    data_bags_path: "test/integration/data_bags"
    attributes: {
      "name": "chef-alfresco-community-52",
      "hostname": "alfresco-allinone-test",
      "alfresco" : {
        "components" : ['haproxy','nginx','tomcat','transform','repo','share','solr','mysql','googledocs','yourkit'],
        "version" : "5.2.d",
        "ssl_enabled" : false
      },
      "nginx" : {
        "use_nossl_config" : true
      },
      "haproxy" : {
        "error_codes": []
        }
     }
  - name: community-solr6-52
    run_list:
      - recipe[alfresco::default]
      - recipe[alfresco::redeploy]
    verifier:
      inspec_tests:
        - name: nginx-hardening
          git: https://github.com/Alfresco/tests-nginx-hardening
    data_bags_path: "test/integration/data_bags"
    attributes: {
      "name": "chef-alfresco-community-52",
      "hostname": "alfresco-allinone-test",
      "alfresco" : {
        "components" : ['haproxy','nginx','tomcat','transform','repo','share','solr6','mysql','googledocs','yourkit'],
        "version" : "5.2.d",
        "ssl_enabled" : false
      },
      "nginx" : {
        "use_nossl_config" : true
      }
     }
  - name: enterprise-edition
    run_list:
      - recipe[alfresco::default]
      - recipe[alfresco::redeploy]
    data_bags_path: "test/integration/data_bags"
    verifier:
      inspec_tests:
        - name: nginx-hardening
          git: https://github.com/Alfresco/tests-nginx-hardening
    attributes: {
      "name": "chef-alfresco-enterprise",
      "hostname": "alfresco-allinone-test",
      "alfresco" : {
        "version" : "5.1.2",
        "components" : ["haproxy","nginx","tomcat","transform","repo","share","solr","mysql","aos", "rm"],
        "edition" : "enterprise",
        "ssl_enabled" : false
      },
      "artifact-deployer" : {
        "maven" : {
          "timeout" : 1500,
          "repositories" : {
            "internal" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/groups/internal",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            },
            "internal-staging" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/repositories/internal-staging",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            }
          }
        }
      },
      "nginx" : {
        "use_nossl_config" : true
      }
     }
  - name: enterprise-52
    run_list:
      - recipe[alfresco::default]
      - recipe[alfresco::redeploy]
    data_bags_path: "test/integration/data_bags"
    verifier:
      inspec_tests:
        - name: nginx-hardening
          git: https://github.com/Alfresco/tests-nginx-hardening
    attributes: {
      "name": "chef-alfresco-enterprise-52",
      "hostname": "alfresco-allinone-test",
      "alfresco" : {
        "version" : "5.2.0",
        "components" : ["haproxy","nginx","tomcat","transform","repo","share","solr","mysql","aos","rm"],
        "edition" : "enterprise",
        "ssl_enabled" : false
      },
      "artifact-deployer" : {
        "maven" : {
          "timeout" : 1500,
          "repositories" : {
            "internal" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/groups/internal",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            },
            "internal-staging" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/repositories/internal-staging",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            },
            "internal-releases" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/repositories/internal-releases",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            },
            "staging" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/groups/staging",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            }
          }
        }
      },
      "nginx" : {
        "use_nossl_config" : true
      }
     }
  - name: enterprise-solr6-52
    run_list:
      - recipe[alfresco::default]
      - recipe[alfresco::redeploy]
    data_bags_path: "test/integration/data_bags"
    verifier:
      inspec_tests:
        - name: nginx-hardening
          git: https://github.com/Alfresco/tests-nginx-hardening
    attributes: {
      "name": "chef-alfresco-enterprise-52",
      "hostname": "alfresco-allinone-test",
      "alfresco" : {
        "version" : "5.2.0",
        "components" : ["haproxy","nginx","tomcat","transform","repo","share","solr6","mysql","aos","rm"],
        "edition" : "enterprise",
        "ssl_enabled" : false
      },
      "artifact-deployer" : {
        "maven" : {
          "timeout" : 1500,
          "repositories" : {
            "internal" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/groups/internal",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            },
            "internal-staging" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/repositories/internal-staging",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            },
            "internal-releases" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/repositories/internal-releases",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            },
            "staging" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/groups/staging",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            }
          }
        }
      },
      "nginx" : {
        "use_nossl_config" : true
      }
     }
