# When editing this file, remember that http://www.yamllint.com is your friend :-)
---

driver_plugin: vagrant
use_vagrant_berkshelf_plugin: true
driver:
  vagrantfile_erb: Vagrantfile.erb

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.0
    driver:
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.0_chef-provisionerless.box
    driver_config:
      require_chef_omnibus: 12.3.0

suites:
  - name: checklist
    run_list:
      - recipe[alfresco::default]
    data_bags_path: "test/integration/data_bags"
    attributes: {
      "name": "img-basic-test",
      "hostname": "alfresco-allinone-test",
      "nginx" : {
        "proxy_set_header_port" : "8800"
      },
      "alfresco" : {
        "properties" : {
           "aos.port" : "8800",
           "ftp.enabled" : true
        },
        "version" : "5.0.1.2"
      },
      "artifact-deployer" : {
        "maven" : {
          "timeout" : 1500
        }
      }
    }
  - name: chef-alfresco
    run_list:
      - recipe[alfresco::default]
    data_bags_path: "test/integration/data_bags"
    attributes: {
      "name": "img-basic-test",
      "hostname": "alfresco-allinone-test",
      "nginx" : {
        "proxy_set_header_port" : "8800"
      },
      "alfresco" : {
        "properties" : {
           "aos.port" : "8800"
        }
      },
      "artifact-deployer" : {
        "maven" : {
          "timeout" : 1500
        }
      }
    }
