# When editing this file, remember that http://www.yamllint.com is your friend :-)
---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero


verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config:
      image: centos:7
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      forward:
      - 80:80
      - 8070:8070
      - 8081:8081
      - 8090:8090
      - 9001:9001
      - 9000:9000

suites:
  - name: community
    run_list:
      - recipe[alfresco::default]
      - recipe[alfresco::redeploy]
    verifier:
      inspec_tests:
        - name: nginx-hardening
          git: https://github.com/Alfresco/tests-nginx-hardening
    data_bags_path: "test/integration/data_bags"
    attributes: {
      "name": "chef-alfresco-community",
      "hostname": "alfresco-allinone-test",
      "alfresco" : {
        "components" : ['haproxy','nginx','tomcat','transform','repo','share','solr','mysql','googledocs','yourkit'],
        "version" : "5.1.g",
        "ssl_enabled" : false
      },
      "nginx" : {
        "use_nossl_config" : true
      }
    }
  - name: enterprise
    run_list:
      - recipe[alfresco::default]
      - recipe[alfresco::redeploy]
    data_bags_path: "test/integration/data_bags"
    verifier:
      inspec_tests:
        - name: nginx-hardening
          git: https://github.com/Alfresco/tests-nginx-hardening
    attributes: {
      "name": "chef-alfresco-enterprise",
      "hostname": "alfresco-allinone-test",
      "alfresco" : {
        "version" : "5.1.2",
        "components" : ["haproxy","nginx","tomcat","transform","repo","share","solr","mysql","aos", "rm",'googledocs','yourkit'],
        "edition" : "enterprise",
        "ssl_enabled" : false
      },
      "artifact-deployer" : {
        "maven" : {
          "timeout" : 1500,
          "repositories" : {
            "internal" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/groups/internal",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            },
            "staging" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/repositories/internal-staging",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            }
          }
        }
      },
      "nginx" : {
        "use_nossl_config" : true
      }
    }
