---
driver:
  name: docker
  privileged: true

platforms:
- name: centos-70
  driver_config:
    image: centos:7
    privileged: true
    run_command: /usr/sbin/init

suites:
  - name: default
    run_list:
      - recipe[alfresco::default]
    data_bags_path: "test/integration/data_bags"
    attributes: {
      "name": "chef-alfresco-testing",
      "hostname": "chef-alfresco-docker-testing",
      "alfresco" : {
        "public_protocol" : "http"
      },
      "commons" : {
        "maven" : {
          "timeout" : 1500,
          "repositories" : {
            "private" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/groups/private",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            }
          }
        }
      },
      "nginx" : {
        "use_nossl_config" : true
      }
    }
