# When editing this file, remember that http://www.yamllint.com is your friend :-)
---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36


verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config:
      image: centos:7
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      require_chef_omnibus: 12.19.36
      forward:
      - 80:80
      - 8070:8070
      - 8081:8081
      - 8090:8090
      - 9001:9001
      - 9000:9000

suites:
  - name: community-edition
    run_list:
      - recipe[alfresco::default]
      - recipe[alfresco::redeploy]
      - recipe[alfresco-utils::node_json]
    verifier:
      inspec_tests:
        - name: nginx-hardening
          git: https://github.com/Alfresco/tests-nginx-hardening
        - name: chef-alfresco-inspec-tomcat
          git: https://github.com/Alfresco/chef-alfresco-inspec-tomcat
          tag: v0.1
        - name: utils
          git: https://github.com/Alfresco/chef-alfresco-inspec-utils
          tag: v0.1
        - name: chef-alfresco-inspec-mysql
          git: https://github.com/Alfresco/chef-alfresco-inspec-mysql.git
          tag: v1.1
        - path: test/integration/community-edition/inspec
    data_bags_path: "test/integration/data_bags"
    attributes: {
      "name": "chef-alfresco-community",
      "hostname": "alfresco-allinone-test",
      "alfresco" : {
        "components" : ['haproxy','nginx','tomcat','transform','repo','share','solr','mysql','googledocs'],
        "version" : "5.1.g"
      },
      "nginx" : {
        "use_nossl_config" : true
      },
      "appserver" : {
        "ssl_enabled" : false
        }
     }
  - name: community-52
    run_list:
      - recipe[alfresco::default]
      - recipe[alfresco::redeploy]
      - recipe[alfresco-utils::node_json]
    verifier:
      inspec_tests:
        - name: nginx-hardening
          git: https://github.com/Alfresco/tests-nginx-hardening
        - name: chef-alfresco-inspec-tomcat
          git: https://github.com/Alfresco/chef-alfresco-inspec-tomcat
          tag: v0.1
        - name: utils
          git: https://github.com/Alfresco/chef-alfresco-inspec-utils
          tag: v0.1
        - name: chef-alfresco-inspec-mysql
          git: https://github.com/Alfresco/chef-alfresco-inspec-mysql.git
          tag: v1.1
    data_bags_path: "test/integration/data_bags"
    attributes: {
      "name": "chef-alfresco-community-52",
      "hostname": "alfresco-allinone-test",
      "alfresco" : {
        "components" : ['haproxy','nginx','tomcat','transform','repo','share','solr','mysql','googledocs'],
        "version" : "5.2.d",
        "ssl_enabled" : false,
        "certs" : {
          "ssl_databag" : "ssl",
          "ssl_databag_item" : "certs"
        }
      },
      "nginx" : {
        "use_nossl_config" : true
      },
      "haproxy" : {
        "error_codes": []
        },
      "appserver" : {
        "ssl_enabled" : false
        }
     }
  - name: community-solr6-52
    run_list:
      - recipe[alfresco::default]
      - recipe[alfresco::redeploy]
      - recipe[alfresco-utils::node_json]
    verifier:
      inspec_tests:
        - name: nginx-hardening
          git: https://github.com/Alfresco/tests-nginx-hardening
        - name: chef-alfresco-inspec-tomcat
          git: https://github.com/Alfresco/chef-alfresco-inspec-tomcat
          tag: v0.1
        - name: utils
          git: https://github.com/Alfresco/chef-alfresco-inspec-utils
          tag: v0.1
        - name: chef-alfresco-inspec-mysql
          git: https://github.com/Alfresco/chef-alfresco-inspec-mysql.git
          tag: v1.1
    data_bags_path: "test/integration/data_bags"
    attributes: {
      "name": "chef-alfresco-community-52",
      "hostname": "alfresco-allinone-test",
      "alfresco" : {
        "components" : ['haproxy','nginx','tomcat','transform','repo','share','solr6','mysql','googledocs'],
        "version" : "5.2.d"
      },
      "nginx" : {
        "use_nossl_config" : true
      },
      "appserver" : {
        "ssl_enabled" : false
        }
     }
  - name: enterprise-edition
    run_list:
      - recipe[alfresco::default]
      - recipe[alfresco::redeploy]
    data_bags_path: "test/integration/data_bags"
    verifier:
      inspec_tests:
        - name: nginx-hardening
          git: https://github.com/Alfresco/tests-nginx-hardening
        - name: chef-alfresco-inspec-tomcat
          git: https://github.com/Alfresco/chef-alfresco-inspec-tomcat
          tag: v0.1
        - name: utils
          git: https://github.com/Alfresco/chef-alfresco-inspec-utils
          tag: v0.1
        - name: chef-alfresco-inspec-mysql
          git: https://github.com/Alfresco/chef-alfresco-inspec-mysql.git
          tag: v1.1
    attributes: {
      "name": "chef-alfresco-enterprise",
      "hostname": "alfresco-allinone-test",
      "alfresco" : {
        "version" : "5.1.2",
        "components" : ["haproxy","nginx","tomcat","transform","repo","share","solr","mysql","aos", "rm", "googledocs"],
        "edition" : "enterprise",
        "ssl_enabled" : false,
        "certs" : {
          "ssl_databag" : "ssl",
          "ssl_databag_item" : "certs"
        }
      },
      "commons" : {
        "maven" : {
          "timeout" : 1500,
          "repositories" : {
            "internal" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/groups/internal",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            },
            "internal-staging" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/repositories/internal-staging",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            }
          }
        }
      },
      "nginx" : {
        "use_nossl_config" : true
      },
      "appserver" : {
        "ssl_enabled" : false
        }
     }
  - name: enterprise-52
    run_list:
      - recipe[alfresco::default]
      - recipe[alfresco::redeploy]
      - recipe[alfresco-utils::node_json]
    data_bags_path: "test/integration/data_bags"
    verifier:
      inspec_tests:
        - name: nginx-hardening
          git: https://github.com/Alfresco/tests-nginx-hardening
        - name: chef-alfresco-inspec-tomcat
          git: https://github.com/Alfresco/chef-alfresco-inspec-tomcat
          tag: v0.1
        - name: utils
          git: https://github.com/Alfresco/chef-alfresco-inspec-utils
          tag: v0.1
        - name: chef-alfresco-inspec-mysql
          git: https://github.com/Alfresco/chef-alfresco-inspec-mysql.git
          tag: v1.1
    attributes: {
      "name": "chef-alfresco-enterprise-52",
      "hostname": "alfresco-allinone-test",
      "alfresco" : {
        "version" : "5.2.0",
        "components" : ["haproxy","nginx","tomcat","transform","repo","share","solr","mysql","aos","rm"],
        "edition" : "enterprise",
        "ssl_enabled" : false,
        "certs" : {
          "ssl_databag" : "ssl",
          "ssl_databag_item" : "certs"
        }
      },
      "commons" : {
        "maven" : {
          "timeout" : 1500,
          "repositories" : {
            "internal" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/groups/internal",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            },
            "internal-staging" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/repositories/internal-staging",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            },
            "internal-releases" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/repositories/internal-releases",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            },
            "staging" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/groups/staging",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            }
          }
        }
      },
      "nginx" : {
        "use_nossl_config" : true
      },
      "appserver" : {
        "ssl_enabled" : false
        }
     }
  - name: enterprise-solr6-52
    run_list:
      - recipe[alfresco::default]
      - recipe[alfresco::redeploy]
      - recipe[alfresco-utils::node_json]
    data_bags_path: "test/integration/data_bags"
    verifier:
      inspec_tests:
        - name: nginx-hardening
          git: https://github.com/Alfresco/tests-nginx-hardening
        - name: chef-alfresco-inspec-tomcat
          git: https://github.com/Alfresco/chef-alfresco-inspec-tomcat
          tag: v0.1
        - name: utils
          git: https://github.com/Alfresco/chef-alfresco-inspec-utils
          tag: v0.1
        - name: chef-alfresco-inspec-mysql
          git: https://github.com/Alfresco/chef-alfresco-inspec-mysql.git
          tag: v1.1
    attributes: {
      "name": "chef-alfresco-enterprise-52",
      "hostname": "alfresco-allinone-test",
      "alfresco" : {
        "version" : "5.2.0",
        "components" : ["haproxy","nginx","tomcat","transform","repo","share","solr6","mysql","aos","rm"],
        "edition" : "enterprise",
        "ssl_enabled" : false,
        "certs" : {
          "ssl_databag" : "ssl",
          "ssl_databag_item" : "certs"
        }
      },
      "commons" : {
        "maven" : {
          "timeout" : 1500,
          "repositories" : {
            "internal" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/groups/internal",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            },
            "internal-staging" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/repositories/internal-staging",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            },
            "internal-releases" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/repositories/internal-releases",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            },
            "staging" : {
              "url" : "https://artifacts.alfresco.com/nexus/content/groups/staging",
              "username" : "<%= ENV['NEXUS_USERNAME'] %>",
              "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
            }
          }
        }
      },
      "nginx" : {
        "use_nossl_config" : true
      },
      "appserver" : {
        "ssl_enabled" : false,
        "run_single_instance" : false
        }
     }
