rvm:
  - 2.2

sudo: true

before_script:
  - source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/0.5.0/scripts/start_docker.sh)

script:
  - bundle exec rake foodcritic
  # Run test-kitchen with docker driver, for example:
  - travis_retry bundle exec rake docker_integration
