rvm: 2.2

sudo: required
services: docker

env:
  matrix:
    - SUITE=community-edition
    - SUITE=community-52
    # - SUITE=community-solr6-52

before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 1.2.20
install: chef exec bundle install

before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

script:
  - chef exec rake default
  # Run test-kitchen with docker driver, for example:
  - chef exec bundle exec rake "integration:docker[$SUITE, test]"
