rvm:
  - 2.2

sudo: true

before_script:
  - source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/0.5.0/scripts/start_docker.sh)

script:
  - foodcritic .
  # Run test-kitchen with docker driver, for example:
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml bundle exec kitchen verify community
