language: ruby
rvm:
  - 2.2

sudo: required
services: docker


before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 0.9.0
install: chef exec bundle install

before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

script:
  - foodcritic .
  # Run test-kitchen with docker driver, for example:
  - KITCHEN_LOCAL_YAML=.kitchen.yml bundle exec kitchen verify community